[tool.black]
line-length = 88
skip-string-normalization = false
target-version = ["py37", "py38", "py39", "py310"]
include = "\\.pyi?$"
exclude = '''
/(
    .git
    | __pycache__
    | build
    | dist
    | migrations
    | .venv
    | .env
    | node_modules
)/
'''

[tool.ruff]
# Enable recommended rules + Flake8 replacements
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
    "C90", # mccabe complexity
    "I",  # isort
    "D",  # pydocstyle
    "B",  # flake8-bugbear
    "G",  # flake8-logging-format
]

# Ignore rules that conflict with Black or are too strict
ignore = [
    "E501",  # Let Black handle line length
    "W503"   # Line break before binary operator
]

line-length = 88
target-version = ["py38"]

# Match Flake8's configuration
max-complexity = 10

exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "migrations",
    ".venv",
    ".env",
    "node_modules",
]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["D"]
